import 'package:cloud_firestore/cloud_firestore.dart';
import '../../domain/entities/booking_entity.dart';
import '../../domain/repositories/booking_repository.dart';
import '../models/booking_model.dart';

class BookingRepositoryImpl implements BookingRepository {
  final FirebaseFirestore _firestore;

  BookingRepositoryImpl(this._firestore);

  @override
  Future<void> createBooking(BookingEntity booking) async {
    final model = BookingModel(
      id: booking.id, // Usually generated by Firestore, but passed here for now
      userId: booking.userId,
      destinationId: booking.destinationId,
      dateStart: booking.dateStart,
      dateEnd: booking.dateEnd,
      totalPrice: booking.totalPrice,
      status: booking.status,
      guests: booking.guests,
    );
    await _firestore
        .collection('bookings')
        .doc(booking.id)
        .set(model.toDocument());
  }

  @override
  Future<List<BookingEntity>> getUserBookings(String userId) async {
    try {
      final snapshot = await _firestore
          .collection('bookings')
          .where('userId', isEqualTo: userId)
          .get();
      return snapshot.docs
          .map((doc) => BookingModel.fromSnapshot(doc))
          .toList();
    } catch (e) {
      return [];
    }
  }
}
